# version: "3.3"
# services:
#   web:
#     image: httpd
#     container_name: mywebservername
#     ports:
#       -"9098:80"
version: '3.3'
services: 
  web: 
    image: httpd
    container_name: mywebservername
    networks:
      - mywebnetwork
    ports:
      - '9098:80'
networks:
  mywebnetwork:
    driver: bridge
  dbnetwork:
   driver: bridge
      

   
 
     